### ISSUE TITLE
Counter glitch can create boats of size 3, 5, 7, etc.

### ISSUE THREAD

**Issue by JackBlair87** [JonathanBuchh/boatavg#2]
It is possible to create configurations of rowing shells that are not usually possible in real life by incrementing the seat counter using the up/down arrows. The calculations ironically still work for any n seats, but this feature may have been unintentional. 

To Recreate:
1. Go to https://buchh.fun/boatavg/ 
2. Type in any number not possible for a boat into the numSeats area (3, 5, 6, 7, 9+)
3. OR Select any number from the dropdown menu and increment from there.

Recommended Fix:
Use a dropdown menu instead of the text input field for seat selection.

**Comment by JackBlair87** [comment]
It's also possible to make a 0 and negative sized boat

**Comment by JonathanBuchh** [comment]
This bug was introduced in #1. @zacbakerr what was the rationale for replacing the drop down menu with the number input?
