### ISSUE TITLE
Estimate pieces 500, 5k, and max watts from 2k time or visa versa using the Rower class

### ISSUE THREAD

**Issue by JackBlair87** [JonathanBuchh/boatavg#3]
@JonathanBuchh it could be a cool thought experiment to use the 2Ks and other times to estimate what your score on the other pieces should be. The Rower class has methods that make this really easy: For example, the predicted 500 time could be .splitOf(2ktime) - 15 (in milliseconds). This could be extended to convert between basically any metric.

**Comment by JonathanBuchh** [comment]
This is a good idea! We can use Paul's law to calculate scores on different pieces.

> Paul's Law says that for a rowing athlete with balanced speed and endurance capabilities, for every doubling of distance the 500m split should increase by five seconds. The form below calculates Paul's Law predicted target times based on a known result.

https://www.machars.net/ already does a lot of calculations. If we wanted, we could implement many of them and it may not require the creation of a new class – just some formulas. The hardest part is probably converting milliseconds to split and split to milliseconds.

**Comment by JackBlair87** [comment]
Implemented in most recent commit, with demo calculations. (RowerMathematics.js)

> console.log("1000m split: " + formatTime(paulsLawSplit(2000, parseTime("7:22.4"), 1000)));
console.log("1000m Time: " + formatTime(paulsLawPiece(2000, parseTime("7:22.4"), 1000)));
console.log("2000m split: " + formatTime(paulsLawSplit(2000, parseTime("7:22.4"), 2000)));
console.log("2000m Time: " + formatTime(paulsLawPiece(2000, parseTime("7:22.4"), 2000)));
console.log("5000m split: " + formatTime(paulsLawSplit(2000, parseTime("7:22.4"), 5000)));
console.log("5000m Time: " + formatTime(paulsLawPiece(2000, parseTime("7:22.4"), 5000)));

Will print

> 1000m split: 1:45.6
1000m Time: 3:31.2
2000m split: 1:50.6
2000m Time: 7:22.4
5000m split: 1:57.2
5000m Time: 19:32.1

These are my predicted Paul's Law Times
