### ISSUE TITLE
Unknown conversion formula for 2k time to maxWatts score?

### ISSUE THREAD

**Issue by JackBlair87** [JonathanBuchh/boatavg#7]
I know every split on the erg has a corresponding wattage (eg A 2K in 7:38 represents 233 watts), so there is obviously a formula from split to watts. But, is there a known formula for 2k to predicted MAX WATTS score? (This is the 7 stroke test)

**Comment by JonathanBuchh** [comment]
I am not currently aware of a 2k to MAX watts score.
